<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-07-06T12:43:06 AMT" name="All Test Suite" finished-at="2020-07-06T12:43:15 AMT" duration-ms="9342">
    <groups>
    </groups>
    <test started-at="2020-07-06T12:43:06 AMT" name="C:/Users/Lenovo/Desktop/D_Facade_pattern_test" finished-at="2020-07-06T12:43:15 AMT" duration-ms="9342">
      <class name="org.example.tests.LoginAndAddTest">
        <test-method signature="loginAndChoseItems()[pri:0, instance:org.example.tests.LoginAndAddTest@4d49af10]" started-at="2020-07-06T12:43:06 AMT" name="loginAndChoseItems" finished-at="2020-07-06T12:43:15 AMT" duration-ms="9240" status="FAIL">
          <exception class="org.example.exception.PageValidationException">
            <message>
              <![CDATA[https://www.saucedemo.com/ validation exception]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.example.exception.PageValidationException: https://www.saucedemo.com/ validation exception
at org.example.Pages.LoginPage.validate(LoginPage.java:57)
at org.example.facades.LoginAddItemsToCartFacade.Login(LoginAddItemsToCartFacade.java:14)
at org.example.tests.LoginAndAddTest.loginAndChoseItems(LoginAndAddTest.java:14)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- org.example.exception.PageValidationException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginAndChoseItems -->
      </class> <!-- org.example.tests.LoginAndAddTest -->
    </test> <!-- C:/Users/Lenovo/Desktop/D_Facade_pattern_test -->
  </suite> <!-- All Test Suite -->
</testng-results>
